name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Use an appropriate version for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # Add other extensions if needed
        # pip install -r requirements.txt      # Install project dependencies

      - name: Build documentation
        run: |
          cd docs
          make html   # Build the Sphinx documentation

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  # Path to the built HTML files
          destination_dir: ""       
